version: '3.8'

services:
  # Test Database
  postgres-test:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - test-network

  # Test Redis
  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    networks:
      - test-network

  # Backend for testing
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://test_user:test_password@postgres-test:5432/test_db
      - REDIS_URL=redis://redis-test:6379
      - JWT_SECRET=test_jwt_secret
    depends_on:
      - postgres-test
      - redis-test
    ports:
      - "4001:4000"
    networks:
      - test-network

  # Frontend for testing
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - NEXT_PUBLIC_API_URL=http://backend-test:4000
      - NEXT_PUBLIC_WS_URL=ws://backend-test:4000
    depends_on:
      - backend-test
    ports:
      - "3001:3000"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge